### PR TITLE
fix: Warn about BTRFS on Unraid

### PR DESCRIPTION
**Pull request by kroese**

### CODE REVIEW

**Comment by Joly0** [comment]
Interesting, didnt knew that. Could you maybe add a link to the information, because i cant find it

**Comment by kroese** [comment]
In this issue 

https://github.com/dockur/windows/issues/299

and this issue

https://github.com/dockur/windows/issues/533

multiple people had issues completing the installation, that disappeared as soon as they switched to ZFS or XFS filesystem on Unraid.

**Comment by Joly0** [comment]
Interesting. Could you please add the link to the template file so others can easily find it aswell?

**Comment by kroese** [comment]
Those are not very good links for that, because those issues also contain other comments about totally unrelated problems, which make it very confusing.

Also this is not an official and confirmed problem, it might depend on the version of Unraid (maybe it is fixed in newer releases for example, I dont know). And I cannot reproduce it on Ubuntu, so it might be related to the RAID that Unraid uses for BTRFS, because on Ubuntu+BTRFS there is no problem.

I just wanted to warn people that IF they experience problems, it might be worth trying to use a different filesystem than BTRFS. As it was the solution for some others.

**Comment by Joly0** [comment]
Good point. Thx for the informations regarding this issue and the pr

**Pull request merged**
